name: CI-CD Pipeline

on:
  push:
    branches:
      - 

jobs:
  deploy:
    runs-on: 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show directory (debug)
        run: ls -la

      - name: Stop existing containers
        run: docker compose down || true

      - name: Build & start containers
        run: docker compose up --build -d

      - name: Show running containers
        run: docker ps
